 DROP TABLE "SALARY";

CREATE TABLE "SALARY" (
	"SALARY_CODE"	VARCHAR2(30)		NULL,
	"SALARY_NAME"	VARCHAR2(50)		NOT NULL,
	"TAXATION_CODE"	NUMBER		NOT NULL,
	"TAX_FREE_CODE"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "SALARY"."SALARY_CODE" IS ''1~N'';

DROP TABLE "MEMBER";

CREATE TABLE "MEMBER" (
	"MEM_CODE"	VARCHAR2(100)		NOT NULL,
	"DEPARTMENT_CODE"	VARCHAR2 (30)		NULL,
	"TEAM_CODE"	NUMBER		NULL,
	"MEM_NAME"	VARCHAR2(50)		NOT NULL,
	"REGI_NUMBER"	VARCHAR2(14)		NULL,
	"GENDER"	CHAR(1)		NOT NULL,
	"PHONE"	VARCHAR2(20)		NULL,
	"EMAIL"	VARCHAR2(100)		NULL,
	"NATIONALITY"	VARCHAR2(50)	DEFAULT '내국인'	NOT NULL,
	"MEM_PIC"	VARCHAR2(255)		NULL,
	"IS_MARRIED"	CHAR(1)		NULL,
	"IS_WORING"	CHAR(1)	DEFAULT '1'	NOT NULL,
	"ADDRESS"	VARCHAR2(255)		NULL,
	"POSITION_CODE"	VARCHAR2 (10)		NOT NULL,
	"HOURLY_WAGE"	NUMBER		NULL
);

COMMENT ON COLUMN "MEMBER"."GENDER" IS 'M / F';

COMMENT ON COLUMN "MEMBER"."MEM_PIC" IS '사진저장URL';

COMMENT ON COLUMN "MEMBER"."IS_MARRIED" IS 'TRUE = 1 FALSE = 0';

COMMENT ON COLUMN "MEMBER"."IS_WORING" IS 'TRUE = 1 FALSE = 0';

DROP TABLE "POSITION";

CREATE TABLE "POSITION" (
	"POSITION_CODE"	VARCHAR2 (10)		NOT NULL,
	"POSITION_NAME"	VARCHAR2 (30)		NULL
);

DROP TABLE "PERSONNELORDER";

CREATE TABLE "PERSONNELORDER" (
	"PER_CODE"	VARCHAR2 (30)		NOT NULL,
	"PER_NAME"	VARCHAR2 (30)		NULL
);

DROP TABLE "CAREERINFO";

CREATE TABLE "CAREERINFO" (
	"CAREER_NUMBER"	NUMBER		NOT NULL,
	"CORPORATE_NAME"	VARCHAR2 (50)		NULL,
	"ENTERING_DATE"	DATE		NULL,
	"RETIREMENT_DATE"	DATE		NULL,
	"POSITION"	VARCHAR2(20)	DEFAULT '사원'	NULL,
	"WORKING_DEPARTMENT"	VARCHAR2 (30)		NULL,
	"REASONS_RETIREMENT"	VARCHAR2 (255)		NULL,
	"MEM_CODE"	VARCHAR2(100)		NOT NULL
);

DROP TABLE "ORDERINFO";

CREATE TABLE "ORDERINFO" (
	"ORDER_NUMBER"	NUMBER		NOT NULL,
	"ORDER_DETAILS"	VARCHAR2 (255)		NULL,
	"REMARKS"	VARCHAR2 (255)		NULL,
	"MEM_CODE"	VARCHAR2(100)		NOT NULL
);

DROP TABLE "TAX_FREE";

CREATE TABLE "TAX_FREE" (
	"TAX_FREE_CODE"	VARCHAR2(30)		NOT NULL,
	"TAX_FREE_NAME"	VARCHAR2(50)		NOT NULL,
	"EXPLANATION"	VHARCHAR2		NULL
);

DROP TABLE "PERSONNELORDERAPPLICATION";

CREATE TABLE "PERSONNELORDERAPPLICATION" (
	"DOC_CODE"	VARCHAR2(255)		NOT NULL,
	"MEM_CODE"	VARCHAR2(100)		NOT NULL,
	"DATE_LEAVE"	DATE		NULL,
	"DATE_REINSTATEMENT"	DATE		NULL,
	"RETIREMENT_DATE"	DATE		NULL,
	"APPLICATION_DEPARTMENT"	VARCHAR2 (30)		NULL,
	"ORDER_DATE"	DATE		NULL,
	"PER_REASON"	VARCHAR2 (255)		NULL,
	"PER_CODE"	VARCHAR2 (30)		NOT NULL
);

COMMENT ON COLUMN "PERSONNELORDERAPPLICATION"."DOC_CODE" IS '년월일+시퀀스';

COMMENT ON COLUMN "PERSONNELORDERAPPLICATION"."MEM_CODE" IS '상신인';

DROP TABLE "INCOME_TAX";

CREATE TABLE "INCOME_TAX" (
	"INCOME_TAX_CODE"	VARCHAR2		NOT NULL,
	"LOWER_TAX_BASE_LIMIT"	NUMBER		NOT NULL,
	"UPPER_TAX_BASE_LIMIT"	NUMBER		NOT NULL,
	"TAX_RATE"	NUMBER		NOT NULL,
	"DEDUCTION_AMOUNT"	NUMBER		NOT NULL
);

DROP TABLE "FOUR_MAJOR_INSURANCES";

CREATE TABLE "FOUR_MAJOR_INSURANCES" (
	"4MJIN_CODES"	VARCHAR2		NOT NULL,
	"PERSONAL_DEDUCTIBLE"	NUMBER		NOT NULL,
	"COMPANY_DEDUCTIBLES"	NUMBER		NOT NULL,
	"STNDR_MNINC_MAX"	NUMBER		NOT NULL,
	"STNDR_MNINC_MIN"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "FOUR_MAJOR_INSURANCES"."4MJIN_CODES" IS 'A국민,B건강,C고용';

DROP TABLE "DEPARTMENT";

CREATE TABLE "DEPARTMENT" (
	"DEPARTMENT_CODE"	VARCHAR2 (30)		NOT NULL,
	"DEPARTMENT_NAME"	VARCHAR2 (30)		NULL
);

DROP TABLE "DEPT_AUTHORITY";

CREATE TABLE "DEPT_AUTHORITY" (
	"AUTH_NUMBER"	NUMBER		NOT NULL,
	"DEPARTMENT_CODE"	VARCHAR2 (30)		NOT NULL,
	"AUTH_NAME"	VARCHAR2(30)		NOT NULL
);

COMMENT ON COLUMN "DEPT_AUTHORITY"."AUTH_NUMBER" IS '시퀀스/경우의수 10개';

COMMENT ON COLUMN "DEPT_AUTHORITY"."AUTH_NAME" IS 'ROLE_ADMIN / ROLE_MEMBER';

DROP TABLE "BONUS";

CREATE TABLE "BONUS" (
	"BONUS_CODE"	VARCHAR2(30)		NOT NULL,
	"BONUS_NAME"	VARCHAR2(50)		NOT NULL,
	"TAXATION_CODE"	VARCHAR2(30)		NOT NULL,
	"TAX_FREE_CODE"	VARCHAR2(30)		NOT NULL
);

DROP TABLE "MEM_AUTHORITY";

CREATE TABLE "MEM_AUTHORITY" (
	"MEM_CODE"	VARCHAR2(100)		NOT NULL,
	"AUTH_NUMBER"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "MEM_AUTHORITY"."AUTH_NUMBER" IS '시퀀스/경우의수 15개';

DROP TABLE "WORK_TASK_ATTACHMENT";

CREATE TABLE "WORK_TASK_ATTACHMENT" (
	"ATTACH_NO"	NUMBER		NOT NULL,
	"TASK_CODE"	NUMBER		NOT NULL,
	"FILE_NAME"	VARCHAR2(255)		NOT NULL,
	"URL"	VARCHAR2(255)		NULL,
	"PATHNAME"	VARCHAR2(255)		NULL
);

COMMENT ON COLUMN "WORK_TASK_ATTACHMENT"."ATTACH_NO" IS '시퀀스';

COMMENT ON COLUMN "WORK_TASK_ATTACHMENT"."TASK_CODE" IS '시퀀스';

DROP TABLE "WORK_PAGE";

CREATE TABLE "WORK_PAGE" (
	"MANAGE_WORKPAGE"	NUMBER		NOT NULL,
	"MEM_CODE"	VARCHAR2(100)		NOT NULL
);

COMMENT ON COLUMN "WORK_PAGE"."MANAGE_WORKPAGE" IS '시퀀스';

DROP TABLE "WORK_GROUP";

CREATE TABLE "WORK_GROUP" (
	"WORK_CODE"	NUMBER		NOT NULL,
	"MANAGE_WORKPAGE"	NUMBER		NOT NULL,
	"GROUP_NAME"	VARCHAR2(100)	DEFAULT '그룹'	NOT NULL
);

COMMENT ON COLUMN "WORK_GROUP"."WORK_CODE" IS '시퀀스';

COMMENT ON COLUMN "WORK_GROUP"."MANAGE_WORKPAGE" IS '시퀀스';

DROP TABLE "WORK_TASK";

CREATE TABLE "WORK_TASK" (
	"TASK_CODE"	NUMBER		NOT NULL,
	"WORK_CODE"	NUMBER		NOT NULL,
	"TASK_NAME"	VARCHAR2(50)		NOT NULL,
	"START_DATE"	DATE		NULL,
	"END_DATE"	DATE		NULL,
	"PROGRESS"	NUMBER	DEFAULT 0	NULL,
	"LINK"	VARCHAR2(255)		NULL,
	"PRIORITY"	VARCHAR2(10)	DEFAULT '낮음'	NULL,
	"F_NUMBER"	VARCHAR2(255)		NULL
);

COMMENT ON COLUMN "WORK_TASK"."TASK_CODE" IS '시퀀스';

COMMENT ON COLUMN "WORK_TASK"."WORK_CODE" IS '시퀀스';

COMMENT ON COLUMN "WORK_TASK"."PROGRESS" IS 'CHECK 0  <= PROGRESS <= 100';

DROP TABLE "OVERTIME_WORK";

CREATE TABLE "OVERTIME_WORK" (
	"OVERTIME_WORK_CODE"	VARCHAR2(30)		NOT NULL,
	"OVERTIME_WORK_NAME"	VARCHAR2(50)		NOT NULL,
	"REWARD_MULTIPLIER"	NUMBER		NOT NULL
);

DROP TABLE "TEAM";

CREATE TABLE "TEAM" (
	"TEAM_CODE"	NUMBER		NOT NULL,
	"DEPARTMENT_CODE"	VARCHAR2 (30)		NOT NULL,
	"TEAM_NAME"	VARCHAR2(255)		NOT NULL
);

COMMENT ON COLUMN "TEAM"."TEAM_CODE" IS '시퀀스';

COMMENT ON COLUMN "TEAM"."TEAM_NAME" IS '팀명(담당프로젝트명 등)';

DROP TABLE "TASK_COMMENTS";

CREATE TABLE "TASK_COMMENTS" (
	"COMMENT_NUM"	VARCHAR(255)		NOT NULL,
	"TASK_CODE"	NUMBER		NOT NULL,
	"MEM_CODE"	VARCHAR2(100)		NOT NULL,
	"CONTENT"	VARCHAR2(500)		NOT NULL,
	"WRITE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"IS_DELETED"	CHAR(1)	DEFAULT 'N'	NOT NULL
);

COMMENT ON COLUMN "TASK_COMMENTS"."COMMENT_NUM" IS '시퀀스';

COMMENT ON COLUMN "TASK_COMMENTS"."TASK_CODE" IS '시퀀스';

COMMENT ON COLUMN "TASK_COMMENTS"."CONTENT" IS '내용';

COMMENT ON COLUMN "TASK_COMMENTS"."WRITE_DATE" IS '작성일';

COMMENT ON COLUMN "TASK_COMMENTS"."IS_DELETED" IS 'Y / N';

DROP TABLE "SEVERANCE_PAY";

CREATE TABLE "SEVERANCE_PAY" (
	"SEVERANCE_PAY_CODE"	VARCHAR2(30)		NOT NULL,
	"MEM_CODE"	VARCHAR2(100)		NOT NULL,
	"RETIREMENT_AMOUNT"	NUMBER		NULL
);

DROP TABLE "TAGED_PERSON";

CREATE TABLE "TAGED_PERSON" (
	"TASK_CODE"	NUMBER		NOT NULL,
	"MEM_CODE"	VARCHAR2(100)		NOT NULL
);

COMMENT ON COLUMN "TAGED_PERSON"."TASK_CODE" IS '시퀀스';

DROP TABLE "WORK_IS_ACTIVE";

CREATE TABLE "WORK_IS_ACTIVE" (
	"MANAGE_WORKPAGE"	NUMBER		NOT NULL,
	"IS_TIMELINE"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"IS_TAGED_PERSON"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"IS_PROGRESS"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"IS_LINK"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"IS_FILE"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"IS_PRIORITY"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"IS_F_NUMBER"	CHAR(1)	DEFAULT 'N'	NOT NULL
);

COMMENT ON COLUMN "WORK_IS_ACTIVE"."MANAGE_WORKPAGE" IS '시퀀스';

DROP TABLE "WORK_SETTING";

CREATE TABLE "WORK_SETTING" (
	"WORK_SETTING_NUMBER"	VARCHAR2 (20)		NOT NULL,
	"BASICWORK_TIME"	VARCHAR2 (50)		NULL,
	"STARTTIME_AVAILWORK"	VARCHAR2 (50)		NULL,
	"ENDTIME_AVAILWORK"	VARCHAR2 (50)		NULL,
	"BASICREST_TIME"	VARCHAR2 (50)		NULL,
	"FIXED_WORKING_HOURS"	NUMBER		NULL,
	"MAXIMUM_OVERTIME_HOURS"	NUMBER		NULL,
	"WORKDAY_RULE"	NUMBER		NULL,
	"WORKTYPE_CODE"	VARCHAR2 (30)		NOT NULL
);

COMMENT ON COLUMN "WORK_SETTING"."WORK_SETTING_NUMBER" IS '시퀀스';

COMMENT ON COLUMN "WORK_SETTING"."WORKTYPE_CODE" IS '시퀀스';

DROP TABLE "APPROVAL";

CREATE TABLE "APPROVAL" (
	"DOC_CODE"	VARCHAR2(255)		NOT NULL,
	"MEM_CODE"	VARCHAR2(100)		NOT NULL,
	"DOC_TYPE"	VARCHAR2(100)		NOT NULL,
	"IS_APPROVED"	CHAR(1)	DEFAULT 'W'	NOT NULL
);

COMMENT ON COLUMN "APPROVAL"."DOC_CODE" IS '년월일+시퀀스';

COMMENT ON COLUMN "APPROVAL"."MEM_CODE" IS '상신인';

COMMENT ON COLUMN "APPROVAL"."DOC_TYPE" IS '결재종류(EX:업무, 근태)';

COMMENT ON COLUMN "APPROVAL"."IS_APPROVED" IS 'W/Y/N';

DROP TABLE "WORKTYPE_CATEGORY";

CREATE TABLE "WORKTYPE_CATEGORY" (
	"WORKTYPE_CODE"	VARCHAR2 (30)		NOT NULL,
	"WORKTYPE_NAME"	VARCHAR2 (50)		NULL
);

COMMENT ON COLUMN "WORKTYPE_CATEGORY"."WORKTYPE_CODE" IS '시퀀스';

DROP TABLE "APPROVER";

CREATE TABLE "APPROVER" (
	"DOC_CODE"	VARCHAR2(255)		NOT NULL,
	"MEM_CODE"	VARCHAR2(100)		NOT NULL,
	"IS_SIGN"	CHAR(1)	DEFAULT 'W'	NOT NULL,
	"PROCESSED_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"OPINION"	VARCHAR2(255)		NULL
);

COMMENT ON COLUMN "APPROVER"."DOC_CODE" IS '년월일+시퀀스';

COMMENT ON COLUMN "APPROVER"."MEM_CODE" IS '결재자';

COMMENT ON COLUMN "APPROVER"."IS_SIGN" IS 'W / Y / N (대기, 승인, 반려)';

COMMENT ON COLUMN "APPROVER"."PROCESSED_DATE" IS '처리된 날짜';

DROP TABLE "REFEREE";

CREATE TABLE "REFEREE" (
	"DOC_CODE"	VARCHAR2(255)		NOT NULL,
	"MEM_CODE"	VARCHAR2(100)		NOT NULL
);

COMMENT ON COLUMN "REFEREE"."DOC_CODE" IS '년월일+시퀀스';

COMMENT ON COLUMN "REFEREE"."MEM_CODE" IS '참조인';

DROP TABLE "BOOKMARK";

CREATE TABLE "BOOKMARK" (
	"DOC_CODE"	VARCHAR2(255)		NOT NULL,
	"MEM_CODE"	VARCHAR2(100)		NOT NULL
);

COMMENT ON COLUMN "BOOKMARK"."DOC_CODE" IS '년월일+시퀀스';

COMMENT ON COLUMN "BOOKMARK"."MEM_CODE" IS '상신인';

DROP TABLE "DOC_ATTACHMENT";

CREATE TABLE "DOC_ATTACHMENT" (
	"ATTACH_NO"	NUMBER		NOT NULL,
	"DOC_CODE"	VARCHAR2(255)		NOT NULL,
	"MEM_CODE"	VARCHAR2(100)		NOT NULL,
	"FILE_NAME"	VARCHAR2(255)		NOT NULL,
	"URL"	VARCHAR2(255)		NULL,
	"PATHNAME"	VARCHAR2(255)		NULL
);

COMMENT ON COLUMN "DOC_ATTACHMENT"."ATTACH_NO" IS '시퀀스';

COMMENT ON COLUMN "DOC_ATTACHMENT"."DOC_CODE" IS '년월일+시퀀스';

COMMENT ON COLUMN "DOC_ATTACHMENT"."MEM_CODE" IS '상신인';

DROP TABLE "APPLICATION_WORK_SCHEDULE";

CREATE TABLE "APPLICATION_WORK_SCHEDULE" (
	"SCHEDULE_NUMBER"	VARCHAR2(20)		NOT NULL,
	"SCHEDULE_START_DATE"	VARCHAR2(50)		NULL,
	"SCHEDULE_APPLICATION_DATE"	DATE		NULL,
	"WORKTYPE_CODE"	VARCHAR2 (30)		NULL,
	"WORK_SETTING_NUMBER"	VARCHAR2 (20)		NOT NULL,
	"MEM_CODE"	VARCHAR2(100)		NOT NULL,
	"REPORTER_TAG_CODE"	VARCHAR2 (10)		NOT NULL,
	"DOCUMENT_NUMBER"	VARCHAR2(30)		NOT NULL
);

COMMENT ON COLUMN "APPLICATION_WORK_SCHEDULE"."SCHEDULE_NUMBER" IS '시퀀스';

COMMENT ON COLUMN "APPLICATION_WORK_SCHEDULE"."SCHEDULE_APPLICATION_DATE" IS 'SYSDATE';

COMMENT ON COLUMN "APPLICATION_WORK_SCHEDULE"."WORK_SETTING_NUMBER" IS '시퀀스';

COMMENT ON COLUMN "APPLICATION_WORK_SCHEDULE"."REPORTER_TAG_CODE" IS '시퀀스';

COMMENT ON COLUMN "APPLICATION_WORK_SCHEDULE"."DOCUMENT_NUMBER" IS '시퀀스';

DROP TABLE "WORK_SCHEDULE";

CREATE TABLE "WORK_SCHEDULE" (
	"WORK_DATE"	DATE		NULL,
	"SCHEDULE_NUMBER"	VARCHAR(20)		NOT NULL,
	"WORK_STARTTIME"	VARCHAR2(50)		NULL,
	"WORK_ENDTIME"	VARCHAR2(50)		NULL,
	"REST_STARTTIME"	VARCHAR2(50)		NULL,
	"REST_ENDTIME"	VARCHAR2(50)		NULL
);

COMMENT ON COLUMN "WORK_SCHEDULE"."SCHEDULE_NUMBER" IS '시퀀스';

DROP TABLE "DAILY_ WAGE";

CREATE TABLE "DAILY_ WAGE" (
	"DAILY _WAGE_CODE"	VARCHAR2(30)		NOT NULL,
	"MEM_CODE"	VARCHAR2(100)		NULL,
	"WORK_DATE"	DATE		NULL,
	"GET_TO_WORK"	DATE		NULL,
	"GET_OFF_WORK"	DATE		NULL,
	"OVERTIME_STARTTIME"	DATE		NULL,
	"OVERTIME_ENDTIME"	DATE		NULL,
	"OVERTIME_WORK_CODE"	VARCHAR2(30)		NULL,
	"REWARD_MULTIPLIER"	NUMBER		NULL,
	"DAILY_SUM"	NUMBER		NULL
);

COMMENT ON COLUMN "DAILY_ WAGE"."WORK_DATE" IS '근태~FK';

COMMENT ON COLUMN "DAILY_ WAGE"."GET_TO_WORK" IS '근태~FK';

COMMENT ON COLUMN "DAILY_ WAGE"."GET_OFF_WORK" IS '근태~FK';

COMMENT ON COLUMN "DAILY_ WAGE"."OVERTIME_STARTTIME" IS '근태~FK';

COMMENT ON COLUMN "DAILY_ WAGE"."OVERTIME_ENDTIME" IS '근태~FK';

DROP TABLE "ATTEND_REGIST";

CREATE TABLE "ATTEND_REGIST" (
	"ATTEND_REGIST_NUMBER"	VARCHAR2(20)		NOT NULL,
	"WORK_DATE"	DATE		NULL,
	"GET_TO_WORK"	DATE		NULL,
	"GET_OFF_WORK"	DATE		NULL,
	"MEM_CODE"	VARCHAR2(100)		NOT NULL
);

COMMENT ON COLUMN "ATTEND_REGIST"."ATTEND_REGIST_NUMBER" IS '시퀀스';

COMMENT ON COLUMN "ATTEND_REGIST"."WORK_DATE" IS 'SYSDATE';

COMMENT ON COLUMN "ATTEND_REGIST"."GET_TO_WORK" IS 'SYSDATE';

COMMENT ON COLUMN "ATTEND_REGIST"."GET_OFF_WORK" IS 'SYSDATE';

DROP TABLE "ADJUSTING_ATTENDANCE";

CREATE TABLE "ADJUSTING_ATTENDANCE" (
	"ADJUST_ATTEND_NUMBER"	VARCHAR2(20)		NOT NULL,
	"ADJUST_APPLICATION_DATE"	DATE		NULL,
	"ADJUST_SCHEDULE_DATE"	VARCHAR2(50)		NULL,
	"ADJUST_STARTTIME"	VARCHAR2(50)		NULL,
	"ADJUST_ENDTIME"	VARCHAR2(50)		NULL,
	"ADJUST_REASON"	VARCHAR2(200)		NULL,
	"SCHEDULE_NUMBER"	VARCHAR2(20)		NOT NULL,
	"REPORTER_TAG_CODE"	VARCHAR2 (10)		NOT NULL,
	"DOCUMENT_NUMBER"	VARCHAR2(30)		NOT NULL
);

COMMENT ON COLUMN "ADJUSTING_ATTENDANCE"."ADJUST_ATTEND_NUMBER" IS '시퀀스';

COMMENT ON COLUMN "ADJUSTING_ATTENDANCE"."ADJUST_APPLICATION_DATE" IS 'SYSDATE';

COMMENT ON COLUMN "ADJUSTING_ATTENDANCE"."SCHEDULE_NUMBER" IS '시퀀스';

COMMENT ON COLUMN "ADJUSTING_ATTENDANCE"."REPORTER_TAG_CODE" IS '시퀀스';

COMMENT ON COLUMN "ADJUSTING_ATTENDANCE"."DOCUMENT_NUMBER" IS '시퀀스';

DROP TABLE "REPORTER_TAG";

CREATE TABLE "REPORTER_TAG" (
	"REPORTER_TAG_CODE"	VARCHAR2 (10)		NOT NULL,
	"MEM_CODE"	VARCHAR2(100)		NOT NULL
);

COMMENT ON COLUMN "REPORTER_TAG"."REPORTER_TAG_CODE" IS '시퀀스';

DROP TABLE "APPLICATION_OVERTIME_WORK";

CREATE TABLE "APPLICATION_OVERTIME_WORK" (
	"OVERTIME_NUMBER"	VARCHAR2(20)		NOT NULL,
	"OVERTIME_APPLICATION_DATE"	DATE		NULL,
	"OVERTIME_SCHEDULE_DATE"	VARCHAR2(100)		NULL,
	"MEM_CODE"	VARCHAR2(100)		NOT NULL,
	"REPORTER_TAG_CODE"	VARCHAR2 (10)		NOT NULL,
	"WORK_SETTING_NUMBER"	VARCHAR2 (20)		NOT NULL,
	"DOCUMENT_NUMBER"	VARCHAR2(30)		NOT NULL
);

COMMENT ON COLUMN "APPLICATION_OVERTIME_WORK"."OVERTIME_NUMBER" IS '시퀀스';

COMMENT ON COLUMN "APPLICATION_OVERTIME_WORK"."OVERTIME_APPLICATION_DATE" IS 'SYSDATE';

COMMENT ON COLUMN "APPLICATION_OVERTIME_WORK"."REPORTER_TAG_CODE" IS '시퀀스';

COMMENT ON COLUMN "APPLICATION_OVERTIME_WORK"."WORK_SETTING_NUMBER" IS '시퀀스';

COMMENT ON COLUMN "APPLICATION_OVERTIME_WORK"."DOCUMENT_NUMBER" IS '시퀀스';

DROP TABLE "ANNUAL_MAKE";

CREATE TABLE "ANNUAL_MAKE" (
	"ANNUAL_MAKE_NUMER"	VARCHAR2(20)		NOT NULL,
	"STANDARD_YEAR"	NUMBER		NULL,
	"ANNUAL_MAKE_DATE"	DATE		NULL,
	"ANNUAL_DAY"	NUMBER		NULL,
	"MONTHLY_LEAVE"	NUMBER		NULL,
	"LASTYEAR _ANNUAL"	NUMBER		NULL,
	"MEM_CODE"	VARCHAR2(100)		NOT NULL
);

COMMENT ON COLUMN "ANNUAL_MAKE"."ANNUAL_MAKE_NUMER" IS '시퀀스';

COMMENT ON COLUMN "ANNUAL_MAKE"."ANNUAL_MAKE_DATE" IS 'SYSDATE';

DROP TABLE "ANNUAL_USE";

CREATE TABLE "ANNUAL_USE" (
	"ANNUAL_USE_NUMBER"	VARCHAR2(20)		NOT NULL,
	"ANNUAL_MAKE_NUMER"	VARCHAR2(20)		NOT NULL,
	"ANNUAL_USE_DAY"	NUMBER		NULL,
	"REMAIN_ANNUAL"	NUMBER		NULL,
	"VACATION_NUBER"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "ANNUAL_USE"."ANNUAL_USE_NUMBER" IS '시퀀스';

COMMENT ON COLUMN "ANNUAL_USE"."ANNUAL_MAKE_NUMER" IS '시퀀스';

COMMENT ON COLUMN "ANNUAL_USE"."VACATION_NUBER" IS '시퀀스';

DROP TABLE "APPLICATION_VACATION";

CREATE TABLE "APPLICATION_VACATION" (
	"VACATION_NUBER"	VARCHAR2(20)		NOT NULL,
	"VACATION_APPLICATION_DATE"	DATE		NULL,
	"VACATION_START_DATE"	DATE		NULL,
	"VACATION_END_DATE"	DATE		NULL,
	"VACATION_REASON"	VARCHAR2(200)		NULL,
	"VACATION_CODE"	VARCHAR2(20)		NOT NULL,
	"ALLDAY_CODE"	VARCHAR2(20)		NOT NULL,
	"REPORTER_TAG_CODE"	VARCHAR2 (10)		NOT NULL,
	"DOCUMENT_NUMBER"	VARCHAR2(30)		NOT NULL
);

COMMENT ON COLUMN "APPLICATION_VACATION"."VACATION_NUBER" IS '시퀀스';

COMMENT ON COLUMN "APPLICATION_VACATION"."VACATION_APPLICATION_DATE" IS 'SYSDATE';

COMMENT ON COLUMN "APPLICATION_VACATION"."VACATION_CODE" IS '시퀀스';

COMMENT ON COLUMN "APPLICATION_VACATION"."ALLDAY_CODE" IS '시퀀스';

COMMENT ON COLUMN "APPLICATION_VACATION"."REPORTER_TAG_CODE" IS '시퀀스';

COMMENT ON COLUMN "APPLICATION_VACATION"."DOCUMENT_NUMBER" IS '시퀀스';

DROP TABLE "APPROVED_CATEGORY";

CREATE TABLE "APPROVED_CATEGORY" (
	"APPROVED__CODE"	VARCHAR2(20)		NOT NULL,
	"APPROVED__NAME"	VARCHAR2(20)		NULL
);

COMMENT ON COLUMN "APPROVED_CATEGORY"."APPROVED__CODE" IS '시퀀스';

DROP TABLE "VACATION_CATEGORY";

CREATE TABLE "VACATION_CATEGORY" (
	"VACATION_CODE"	VARCHAR2(20)		NOT NULL,
	"VACATION_NAME"	VARCHAR2(30)		NULL
);

COMMENT ON COLUMN "VACATION_CATEGORY"."VACATION_CODE" IS '시퀀스';

DROP TABLE "ALLDAY_CATEGORY";

CREATE TABLE "ALLDAY_CATEGORY" (
	"ALLDAY_CODE"	VARCHAR2(20)		NOT NULL,
	"ALLDAY_NAME"	VARCHAR2(20)		NULL
);

COMMENT ON COLUMN "ALLDAY_CATEGORY"."ALLDAY_CODE" IS '시퀀스';

DROP TABLE "TAXATION";

CREATE TABLE "TAXATION" (
	"TAXATION_CODE"	VARCHAR2(30)		NOT NULL,
	"TAXATION_NAME"	VARCHAR2(50)		NOT NULL,
	"TAX_RATE"	NUMBER		NULL
);

DROP TABLE "NARACHATTING";

CREATE TABLE "NARACHATTING" (
	"CHAT_NO"	INT		NOT NULL,
	"CHAT_ROOM_NO"	INT		NOT NULL,
	"CHAT_SEND_NICK"	VARCHAR(50)		NULL,
	"CHAT_SEND_TIME"	DATETIME		NULL,
	"CHAT_CONTENT"	VARCHAR(1000)		NULL,
	"CHAT_READ_CHK"	INT		NULL
);

DROP TABLE "AUTHORITY";

CREATE TABLE "AUTHORITY" (
	"AUTH_NAME"	VARCHAR2(30)		NOT NULL,
	"AUTH_CODE"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "AUTHORITY"."AUTH_NAME" IS 'ROLE_ADMIN / ROLE_MEMBER';

COMMENT ON COLUMN "AUTHORITY"."AUTH_CODE" IS '0/1 / 2  - 접근불가/읽기/매니징';

DROP TABLE "DOCUMENT_APPROVAL";

CREATE TABLE "DOCUMENT_APPROVAL" (
	"DOCUMENT_NUMBER"	VARCHAR2(30)		NOT NULL,
	"APPROVED_DATE"	DATE		NULL,
	"REASONS"	VARCHAR2(200)		NULL,
	"APPROVED__CODE"	VARCHAR2(20)		NOT NULL,
	"VACATION_NUBER"	VARCHAR2(20)		NULL,
	"OVERTIME_NUMBER"	VARCHAR2(20)		NULL,
	"ADJUST_ATTEND_NUMBER"	VARCHAR2(20)		NULL,
	"SCHEDULE_NUMBER"	VARCHAR2(20)		NULL
);

COMMENT ON COLUMN "DOCUMENT_APPROVAL"."DOCUMENT_NUMBER" IS '시퀀스';

COMMENT ON COLUMN "DOCUMENT_APPROVAL"."APPROVED_DATE" IS 'SYSDATE';

COMMENT ON COLUMN "DOCUMENT_APPROVAL"."APPROVED__CODE" IS '시퀀스';

COMMENT ON COLUMN "DOCUMENT_APPROVAL"."VACATION_NUBER" IS '시퀀스';

COMMENT ON COLUMN "DOCUMENT_APPROVAL"."OVERTIME_NUMBER" IS '시퀀스';

COMMENT ON COLUMN "DOCUMENT_APPROVAL"."ADJUST_ATTEND_NUMBER" IS '시퀀스';

COMMENT ON COLUMN "DOCUMENT_APPROVAL"."SCHEDULE_NUMBER" IS '시퀀스';

DROP TABLE "BONUS_LIST";

CREATE TABLE "BONUS_LIST" (
	"AWARD_CODE"	VARCHAR2(30)		NOT NULL,
	"MEM_CODE"	VARCHAR2(100)		NOT NULL,
	"BONUS_CODE"	VARCHAR2		NOT NULL,
	"BONUS_AMOUNT"	NUMBER		NULL,
	"PAYMENT_DATE"	DATE		NOT NULL,
	"TAXATION_CODE"	VARCHAR2(30)		NOT NULL,
	"TAX_FREE_CODE"	VARCHAR2(30)		NOT NULL
);

DROP TABLE "CCAPPLICATION";

CREATE TABLE "CCAPPLICATION" (
	"DOC_CODE"	VARCHAR2(255)		NOT NULL,
	"MEM_CODE"	VARCHAR2(100)		NOT NULL,
	"CC_CODE"	VARCHAR2 (30)		NOT NULL
);

COMMENT ON COLUMN "CCAPPLICATION"."DOC_CODE" IS '년월일+시퀀스';

COMMENT ON COLUMN "CCAPPLICATION"."MEM_CODE" IS '상신인';

DROP TABLE "EXPENSECONGRATULATIONSCONDOLENCES";

CREATE TABLE "EXPENSECONGRATULATIONSCONDOLENCES" (
	"CC_CODE"	VARCHAR2 (30)		NOT NULL,
	"CC_NAME"	VARCHAR2 (30)		NULL
);

DROP TABLE "CERTIFICATEAPPLICATION";

CREATE TABLE "CERTIFICATEAPPLICATION" (
	"DOC_CODE"	VARCHAR2(255)		NOT NULL,
	"MEM_CODE"	VARCHAR2(100)		NOT NULL,
	"CER_REASON"	VARCHAR2 (255)		NULL,
	"CER_CODE"	VARCHAR2 (30)		NOT NULL
);

COMMENT ON COLUMN "CERTIFICATEAPPLICATION"."DOC_CODE" IS '년월일+시퀀스';

COMMENT ON COLUMN "CERTIFICATEAPPLICATION"."MEM_CODE" IS '상신인';

DROP TABLE "CERTIFICATE";

CREATE TABLE "CERTIFICATE" (
	"CER_CODE"	VARCHAR2 (30)		NOT NULL,
	"CER_NAME"	VARCHAR2 (30)		NULL
);

DROP TABLE "ANNUAL_INCOME";

CREATE TABLE "ANNUAL_INCOME" (
	"ANNUAL_SALARY_CODE"	NUMBER		NOT NULL,
	"MEM_CODE"	VARCHAR2(100)		NOT NULL,
	"PAYMENT_YEAR"	DATE		NULL,
	"ANNUAL_SALARY"	NUMBER		NULL,
	"REAL_SALARY"	NUMBER		NULL
);

DROP TABLE "MONTHLY_WAGE";

CREATE TABLE "MONTHLY_WAGE" (
	"MONTHLY_WAGE_CODE"	NUMBER		NOT NULL,
	"MEM_CODE"	VARCHAR2(100)		NOT NULL,
	"MONTHLY_PAYCHECK"	NUMBER	DEFAULT 0	NOT NULL,
	"NET_SALARY"	NUMBER		NOT NULL,
	"PAYMENT_DATE"	DATE		NOT NULL,
	"BONUS_SUM"	NUMBER		NULL
);

COMMENT ON COLUMN "MONTHLY_WAGE"."MONTHLY_WAGE_CODE" IS '시퀀스';

DROP TABLE "EMPLOYEE_SALARY_SETTING";

CREATE TABLE "EMPLOYEE_SALARY_SETTING" (
	"SALARY_SETTING_CODE"	VARCHAR2(30)		NOT NULL,
	"MEM_CODE"	VARCHAR2(100)		NOT NULL,
	"BANK"	VARCHAR2 (30)		NULL,
	"ACCOUNT_NUMBER"	VARCHAR2(50)		NULL,
	"SETTING_DATE"	DATE		NOT NULL
);

DROP TABLE "NARAADMIN";

CREATE TABLE "NARAADMIN" (
	"LOGIN"	VARCHAR(225)		NULL,
	"LOGOUT"	VARCHAR(255)		NOT NULL,
	"FIND_PW"	VARCHAR(255)		NULL
);

DROP TABLE "NARAMEMBER";

CREATE TABLE "NARAMEMBER" (
	"ID"	INT		NOT NULL,
	"MEMBER_NAME"	VARCHAR(20)		NULL,
	"MEMBER_EMAIL"	VARCHAR(100)		NULL,
	"MODIFYINFO"	VARCHAR(600)		NULL,
	"MEMBER_PW"	INT		NULL
);

ALTER TABLE "SALARY" ADD CONSTRAINT "PK_SALARY" PRIMARY KEY (
	"SALARY_CODE"
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"MEM_CODE"
);

ALTER TABLE "POSITION" ADD CONSTRAINT "PK_POSITION" PRIMARY KEY (
	"POSITION_CODE"
);

ALTER TABLE "PERSONNELORDER" ADD CONSTRAINT "PK_PERSONNELORDER" PRIMARY KEY (
	"PER_CODE"
);

ALTER TABLE "CAREERINFO" ADD CONSTRAINT "PK_CAREERINFO" PRIMARY KEY (
	"CAREER_NUMBER"
);

ALTER TABLE "ORDERINFO" ADD CONSTRAINT "PK_ORDERINFO" PRIMARY KEY (
	"ORDER_NUMBER"
);

ALTER TABLE "TAX_FREE" ADD CONSTRAINT "PK_TAX_FREE" PRIMARY KEY (
	"TAX_FREE_CODE"
);

ALTER TABLE "PERSONNELORDERAPPLICATION" ADD CONSTRAINT "PK_PERSONNELORDERAPPLICATION" PRIMARY KEY (
	"DOC_CODE",
	"MEM_CODE"
);

ALTER TABLE "INCOME_TAX" ADD CONSTRAINT "PK_INCOME_TAX" PRIMARY KEY (
	"INCOME_TAX_CODE"
);

ALTER TABLE "FOUR_MAJOR_INSURANCES" ADD CONSTRAINT "PK_FOUR_MAJOR_INSURANCES" PRIMARY KEY (
	"4MJIN_CODES"
);

ALTER TABLE "DEPARTMENT" ADD CONSTRAINT "PK_DEPARTMENT" PRIMARY KEY (
	"DEPARTMENT_CODE"
);

ALTER TABLE "DEPT_AUTHORITY" ADD CONSTRAINT "PK_DEPT_AUTHORITY" PRIMARY KEY (
	"AUTH_NUMBER"
);

ALTER TABLE "BONUS" ADD CONSTRAINT "PK_BONUS" PRIMARY KEY (
	"BONUS_CODE"
);

ALTER TABLE "MEM_AUTHORITY" ADD CONSTRAINT "PK_MEM_AUTHORITY" PRIMARY KEY (
	"MEM_CODE",
	"AUTH_NUMBER"
);

ALTER TABLE "WORK_TASK_ATTACHMENT" ADD CONSTRAINT "PK_WORK_TASK_ATTACHMENT" PRIMARY KEY (
	"ATTACH_NO"
);

ALTER TABLE "WORK_PAGE" ADD CONSTRAINT "PK_WORK_PAGE" PRIMARY KEY (
	"MANAGE_WORKPAGE"
);

ALTER TABLE "WORK_GROUP" ADD CONSTRAINT "PK_WORK_GROUP" PRIMARY KEY (
	"WORK_CODE"
);

ALTER TABLE "WORK_TASK" ADD CONSTRAINT "PK_WORK_TASK" PRIMARY KEY (
	"TASK_CODE"
);

ALTER TABLE "OVERTIME_WORK" ADD CONSTRAINT "PK_OVERTIME_WORK" PRIMARY KEY (
	"OVERTIME_WORK_CODE"
);

ALTER TABLE "TEAM" ADD CONSTRAINT "PK_TEAM" PRIMARY KEY (
	"TEAM_CODE"
);

ALTER TABLE "TASK_COMMENTS" ADD CONSTRAINT "PK_TASK_COMMENTS" PRIMARY KEY (
	"COMMENT_NUM"
);

ALTER TABLE "SEVERANCE_PAY" ADD CONSTRAINT "PK_SEVERANCE_PAY" PRIMARY KEY (
	"SEVERANCE_PAY_CODE"
);

ALTER TABLE "TAGED_PERSON" ADD CONSTRAINT "PK_TAGED_PERSON" PRIMARY KEY (
	"TASK_CODE",
	"MEM_CODE"
);

ALTER TABLE "WORK_IS_ACTIVE" ADD CONSTRAINT "PK_WORK_IS_ACTIVE" PRIMARY KEY (
	"MANAGE_WORKPAGE"
);

ALTER TABLE "WORK_SETTING" ADD CONSTRAINT "PK_WORK_SETTING" PRIMARY KEY (
	"WORK_SETTING_NUMBER"
);

ALTER TABLE "APPROVAL" ADD CONSTRAINT "PK_APPROVAL" PRIMARY KEY (
	"DOC_CODE",
	"MEM_CODE"
);

ALTER TABLE "WORKTYPE_CATEGORY" ADD CONSTRAINT "PK_WORKTYPE_CATEGORY" PRIMARY KEY (
	"WORKTYPE_CODE"
);

ALTER TABLE "APPROVER" ADD CONSTRAINT "PK_APPROVER" PRIMARY KEY (
	"DOC_CODE",
	"MEM_CODE"
);

ALTER TABLE "REFEREE" ADD CONSTRAINT "PK_REFEREE" PRIMARY KEY (
	"DOC_CODE",
	"MEM_CODE"
);

ALTER TABLE "BOOKMARK" ADD CONSTRAINT "PK_BOOKMARK" PRIMARY KEY (
	"DOC_CODE",
	"MEM_CODE"
);

ALTER TABLE "DOC_ATTACHMENT" ADD CONSTRAINT "PK_DOC_ATTACHMENT" PRIMARY KEY (
	"ATTACH_NO",
	"DOC_CODE",
	"MEM_CODE"
);

ALTER TABLE "APPLICATION_WORK_SCHEDULE" ADD CONSTRAINT "PK_APPLICATION_WORK_SCHEDULE" PRIMARY KEY (
	"SCHEDULE_NUMBER"
);

ALTER TABLE "WORK_SCHEDULE" ADD CONSTRAINT "PK_WORK_SCHEDULE" PRIMARY KEY (
	"WORK_DATE",
	"SCHEDULE_NUMBER"
);

ALTER TABLE "DAILY_ WAGE" ADD CONSTRAINT "PK_DAILY_ WAGE" PRIMARY KEY (
	"DAILY _WAGE_CODE"
);

ALTER TABLE "ATTEND_REGIST" ADD CONSTRAINT "PK_ATTEND_REGIST" PRIMARY KEY (
	"ATTEND_REGIST_NUMBER"
);

ALTER TABLE "ADJUSTING_ATTENDANCE" ADD CONSTRAINT "PK_ADJUSTING_ATTENDANCE" PRIMARY KEY (
	"ADJUST_ATTEND_NUMBER"
);

ALTER TABLE "REPORTER_TAG" ADD CONSTRAINT "PK_REPORTER_TAG" PRIMARY KEY (
	"REPORTER_TAG_CODE"
);

ALTER TABLE "APPLICATION_OVERTIME_WORK" ADD CONSTRAINT "PK_APPLICATION_OVERTIME_WORK" PRIMARY KEY (
	"OVERTIME_NUMBER"
);

ALTER TABLE "ANNUAL_MAKE" ADD CONSTRAINT "PK_ANNUAL_MAKE" PRIMARY KEY (
	"ANNUAL_MAKE_NUMER"
);

ALTER TABLE "ANNUAL_USE" ADD CONSTRAINT "PK_ANNUAL_USE" PRIMARY KEY (
	"ANNUAL_USE_NUMBER",
	"ANNUAL_MAKE_NUMER"
);

ALTER TABLE "APPLICATION_VACATION" ADD CONSTRAINT "PK_APPLICATION_VACATION" PRIMARY KEY (
	"VACATION_NUBER"
);

ALTER TABLE "APPROVED_CATEGORY" ADD CONSTRAINT "PK_APPROVED_CATEGORY" PRIMARY KEY (
	"APPROVED__CODE"
);

ALTER TABLE "VACATION_CATEGORY" ADD CONSTRAINT "PK_VACATION_CATEGORY" PRIMARY KEY (
	"VACATION_CODE"
);

ALTER TABLE "ALLDAY_CATEGORY" ADD CONSTRAINT "PK_ALLDAY_CATEGORY" PRIMARY KEY (
	"ALLDAY_CODE"
);

ALTER TABLE "TAXATION" ADD CONSTRAINT "PK_TAXATION" PRIMARY KEY (
	"TAXATION_CODE"
);

ALTER TABLE "NARACHATTING" ADD CONSTRAINT "PK_NARACHATTING" PRIMARY KEY (
	"CHAT_NO"
);

ALTER TABLE "AUTHORITY" ADD CONSTRAINT "PK_AUTHORITY" PRIMARY KEY (
	"AUTH_NAME"
);

ALTER TABLE "DOCUMENT_APPROVAL" ADD CONSTRAINT "PK_DOCUMENT_APPROVAL" PRIMARY KEY (
	"DOCUMENT_NUMBER"
);

ALTER TABLE "BONUS_LIST" ADD CONSTRAINT "PK_BONUS_LIST" PRIMARY KEY (
	"AWARD_CODE"
);

ALTER TABLE "CCAPPLICATION" ADD CONSTRAINT "PK_CCAPPLICATION" PRIMARY KEY (
	"DOC_CODE",
	"MEM_CODE"
);

ALTER TABLE "EXPENSECONGRATULATIONSCONDOLENCES" ADD CONSTRAINT "PK_EXPENSECONGRATULATIONSCONDOLENCES" PRIMARY KEY (
	"CC_CODE"
);

ALTER TABLE "CERTIFICATEAPPLICATION" ADD CONSTRAINT "PK_CERTIFICATEAPPLICATION" PRIMARY KEY (
	"DOC_CODE",
	"MEM_CODE"
);

ALTER TABLE "CERTIFICATE" ADD CONSTRAINT "PK_CERTIFICATE" PRIMARY KEY (
	"CER_CODE"
);

ALTER TABLE "ANNUAL_INCOME" ADD CONSTRAINT "PK_ANNUAL_INCOME" PRIMARY KEY (
	"ANNUAL_SALARY_CODE"
);

ALTER TABLE "MONTHLY_WAGE" ADD CONSTRAINT "PK_MONTHLY_WAGE" PRIMARY KEY (
	"MONTHLY_WAGE_CODE"
);

ALTER TABLE "EMPLOYEE_SALARY_SETTING" ADD CONSTRAINT "PK_EMPLOYEE_SALARY_SETTING" PRIMARY KEY (
	"SALARY_SETTING_CODE"
);

ALTER TABLE "NARAMEMBER" ADD CONSTRAINT "PK_NARAMEMBER" PRIMARY KEY (
	"ID"
);

ALTER TABLE "SALARY" ADD CONSTRAINT "FK_TAXATION_TO_SALARY_1" FOREIGN KEY (
	"TAXATION_CODE"
)
REFERENCES "TAXATION" (
	"TAXATION_CODE"
);

ALTER TABLE "SALARY" ADD CONSTRAINT "FK_TAX_FREE_TO_SALARY_1" FOREIGN KEY (
	"TAX_FREE_CODE"
)
REFERENCES "TAX_FREE" (
	"TAX_FREE_CODE"
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "FK_DEPARTMENT_TO_MEMBER_1" FOREIGN KEY (
	"DEPARTMENT_CODE"
)
REFERENCES "DEPARTMENT" (
	"DEPARTMENT_CODE"
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "FK_TEAM_TO_MEMBER_1" FOREIGN KEY (
	"TEAM_CODE"
)
REFERENCES "TEAM" (
	"TEAM_CODE"
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "FK_POSITION_TO_MEMBER_1" FOREIGN KEY (
	"POSITION_CODE"
)
REFERENCES "POSITION" (
	"POSITION_CODE"
);

ALTER TABLE "CAREERINFO" ADD CONSTRAINT "FK_MEMBER_TO_CAREERINFO_1" FOREIGN KEY (
	"MEM_CODE"
)
REFERENCES "MEMBER" (
	"MEM_CODE"
);

ALTER TABLE "ORDERINFO" ADD CONSTRAINT "FK_MEMBER_TO_ORDERINFO_1" FOREIGN KEY (
	"MEM_CODE"
)
REFERENCES "MEMBER" (
	"MEM_CODE"
);

ALTER TABLE "PERSONNELORDERAPPLICATION" ADD CONSTRAINT "FK_APPROVAL_TO_PERSONNELORDERAPPLICATION_1" FOREIGN KEY (
	"DOC_CODE"
)
REFERENCES "APPROVAL" (
	"DOC_CODE"
);

ALTER TABLE "PERSONNELORDERAPPLICATION" ADD CONSTRAINT "FK_APPROVAL_TO_PERSONNELORDERAPPLICATION_2" FOREIGN KEY (
	"MEM_CODE"
)
REFERENCES "APPROVAL" (
	"MEM_CODE"
);

ALTER TABLE "PERSONNELORDERAPPLICATION" ADD CONSTRAINT "FK_PERSONNELORDER_TO_PERSONNELORDERAPPLICATION_1" FOREIGN KEY (
	"PER_CODE"
)
REFERENCES "PERSONNELORDER" (
	"PER_CODE"
);

ALTER TABLE "DEPT_AUTHORITY" ADD CONSTRAINT "FK_DEPARTMENT_TO_DEPT_AUTHORITY_1" FOREIGN KEY (
	"DEPARTMENT_CODE"
)
REFERENCES "DEPARTMENT" (
	"DEPARTMENT_CODE"
);

ALTER TABLE "DEPT_AUTHORITY" ADD CONSTRAINT "FK_AUTHORITY_TO_DEPT_AUTHORITY_1" FOREIGN KEY (
	"AUTH_NAME"
)
REFERENCES "AUTHORITY" (
	"AUTH_NAME"
);

ALTER TABLE "BONUS" ADD CONSTRAINT "FK_TAXATION_TO_BONUS_1" FOREIGN KEY (
	"TAXATION_CODE"
)
REFERENCES "TAXATION" (
	"TAXATION_CODE"
);

ALTER TABLE "BONUS" ADD CONSTRAINT "FK_TAX_FREE_TO_BONUS_1" FOREIGN KEY (
	"TAX_FREE_CODE"
)
REFERENCES "TAX_FREE" (
	"TAX_FREE_CODE"
);

ALTER TABLE "MEM_AUTHORITY" ADD CONSTRAINT "FK_MEMBER_TO_MEM_AUTHORITY_1" FOREIGN KEY (
	"MEM_CODE"
)
REFERENCES "MEMBER" (
	"MEM_CODE"
);

ALTER TABLE "MEM_AUTHORITY" ADD CONSTRAINT "FK_DEPT_AUTHORITY_TO_MEM_AUTHORITY_1" FOREIGN KEY (
	"AUTH_NUMBER"
)
REFERENCES "DEPT_AUTHORITY" (
	"AUTH_NUMBER"
);

ALTER TABLE "WORK_TASK_ATTACHMENT" ADD CONSTRAINT "FK_WORK_TASK_TO_WORK_TASK_ATTACHMENT_1" FOREIGN KEY (
	"TASK_CODE"
)
REFERENCES "WORK_TASK" (
	"TASK_CODE"
);

ALTER TABLE "WORK_PAGE" ADD CONSTRAINT "FK_MEMBER_TO_WORK_PAGE_1" FOREIGN KEY (
	"MEM_CODE"
)
REFERENCES "MEMBER" (
	"MEM_CODE"
);

ALTER TABLE "WORK_GROUP" ADD CONSTRAINT "FK_WORK_PAGE_TO_WORK_GROUP_1" FOREIGN KEY (
	"MANAGE_WORKPAGE"
)
REFERENCES "WORK_PAGE" (
	"MANAGE_WORKPAGE"
);

ALTER TABLE "WORK_TASK" ADD CONSTRAINT "FK_WORK_GROUP_TO_WORK_TASK_1" FOREIGN KEY (
	"WORK_CODE"
)
REFERENCES "WORK_GROUP" (
	"WORK_CODE"
);

ALTER TABLE "TEAM" ADD CONSTRAINT "FK_DEPARTMENT_TO_TEAM_1" FOREIGN KEY (
	"DEPARTMENT_CODE"
)
REFERENCES "DEPARTMENT" (
	"DEPARTMENT_CODE"
);

ALTER TABLE "TASK_COMMENTS" ADD CONSTRAINT "FK_WORK_TASK_TO_TASK_COMMENTS_1" FOREIGN KEY (
	"TASK_CODE"
)
REFERENCES "WORK_TASK" (
	"TASK_CODE"
);

ALTER TABLE "TASK_COMMENTS" ADD CONSTRAINT "FK_MEMBER_TO_TASK_COMMENTS_1" FOREIGN KEY (
	"MEM_CODE"
)
REFERENCES "MEMBER" (
	"MEM_CODE"
);

ALTER TABLE "SEVERANCE_PAY" ADD CONSTRAINT "FK_MEMBER_TO_SEVERANCE_PAY_1" FOREIGN KEY (
	"MEM_CODE"
)
REFERENCES "MEMBER" (
	"MEM_CODE"
);

ALTER TABLE "TAGED_PERSON" ADD CONSTRAINT "FK_WORK_TASK_TO_TAGED_PERSON_1" FOREIGN KEY (
	"TASK_CODE"
)
REFERENCES "WORK_TASK" (
	"TASK_CODE"
);

ALTER TABLE "TAGED_PERSON" ADD CONSTRAINT "FK_MEMBER_TO_TAGED_PERSON_1" FOREIGN KEY (
	"MEM_CODE"
)
REFERENCES "MEMBER" (
	"MEM_CODE"
);

ALTER TABLE "WORK_IS_ACTIVE" ADD CONSTRAINT "FK_WORK_PAGE_TO_WORK_IS_ACTIVE_1" FOREIGN KEY (
	"MANAGE_WORKPAGE"
)
REFERENCES "WORK_PAGE" (
	"MANAGE_WORKPAGE"
);

ALTER TABLE "WORK_SETTING" ADD CONSTRAINT "FK_WORKTYPE_CATEGORY_TO_WORK_SETTING_1" FOREIGN KEY (
	"WORKTYPE_CODE"
)
REFERENCES "WORKTYPE_CATEGORY" (
	"WORKTYPE_CODE"
);

ALTER TABLE "APPROVAL" ADD CONSTRAINT "FK_MEMBER_TO_APPROVAL_1" FOREIGN KEY (
	"MEM_CODE"
)
REFERENCES "MEMBER" (
	"MEM_CODE"
);

ALTER TABLE "APPROVER" ADD CONSTRAINT "FK_APPROVAL_TO_APPROVER_1" FOREIGN KEY (
	"DOC_CODE"
)
REFERENCES "APPROVAL" (
	"DOC_CODE"
);

ALTER TABLE "APPROVER" ADD CONSTRAINT "FK_APPROVAL_TO_APPROVER_2" FOREIGN KEY (
	"MEM_CODE"
)
REFERENCES "APPROVAL" (
	"MEM_CODE"
);

ALTER TABLE "REFEREE" ADD CONSTRAINT "FK_APPROVAL_TO_REFEREE_1" FOREIGN KEY (
	"DOC_CODE"
)
REFERENCES "APPROVAL" (
	"DOC_CODE"
);

ALTER TABLE "REFEREE" ADD CONSTRAINT "FK_APPROVAL_TO_REFEREE_2" FOREIGN KEY (
	"MEM_CODE"
)
REFERENCES "APPROVAL" (
	"MEM_CODE"
);

ALTER TABLE "BOOKMARK" ADD CONSTRAINT "FK_APPROVAL_TO_BOOKMARK_1" FOREIGN KEY (
	"DOC_CODE"
)
REFERENCES "APPROVAL" (
	"DOC_CODE"
);

ALTER TABLE "BOOKMARK" ADD CONSTRAINT "FK_APPROVAL_TO_BOOKMARK_2" FOREIGN KEY (
	"MEM_CODE"
)
REFERENCES "APPROVAL" (
	"MEM_CODE"
);

ALTER TABLE "DOC_ATTACHMENT" ADD CONSTRAINT "FK_APPROVAL_TO_DOC_ATTACHMENT_1" FOREIGN KEY (
	"DOC_CODE"
)
REFERENCES "APPROVAL" (
	"DOC_CODE"
);

ALTER TABLE "DOC_ATTACHMENT" ADD CONSTRAINT "FK_APPROVAL_TO_DOC_ATTACHMENT_2" FOREIGN KEY (
	"MEM_CODE"
)
REFERENCES "APPROVAL" (
	"MEM_CODE"
);

ALTER TABLE "APPLICATION_WORK_SCHEDULE" ADD CONSTRAINT "FK_WORK_SETTING_TO_APPLICATION_WORK_SCHEDULE_1" FOREIGN KEY (
	"WORK_SETTING_NUMBER"
)
REFERENCES "WORK_SETTING" (
	"WORK_SETTING_NUMBER"
);

ALTER TABLE "APPLICATION_WORK_SCHEDULE" ADD CONSTRAINT "FK_MEMBER_TO_APPLICATION_WORK_SCHEDULE_1" FOREIGN KEY (
	"MEM_CODE"
)
REFERENCES "MEMBER" (
	"MEM_CODE"
);

ALTER TABLE "APPLICATION_WORK_SCHEDULE" ADD CONSTRAINT "FK_REPORTER_TAG_TO_APPLICATION_WORK_SCHEDULE_1" FOREIGN KEY (
	"REPORTER_TAG_CODE"
)
REFERENCES "REPORTER_TAG" (
	"REPORTER_TAG_CODE"
);

ALTER TABLE "APPLICATION_WORK_SCHEDULE" ADD CONSTRAINT "FK_DOCUMENT_APPROVAL_TO_APPLICATION_WORK_SCHEDULE_1" FOREIGN KEY (
	"DOCUMENT_NUMBER"
)
REFERENCES "DOCUMENT_APPROVAL" (
	"DOCUMENT_NUMBER"
);

ALTER TABLE "WORK_SCHEDULE" ADD CONSTRAINT "FK_APPLICATION_WORK_SCHEDULE_TO_WORK_SCHEDULE_1" FOREIGN KEY (
	"SCHEDULE_NUMBER"
)
REFERENCES "APPLICATION_WORK_SCHEDULE" (
	"SCHEDULE_NUMBER"
);

ALTER TABLE "DAILY_ WAGE" ADD CONSTRAINT "FK_MEMBER_TO_DAILY_ WAGE_1" FOREIGN KEY (
	"MEM_CODE"
)
REFERENCES "MEMBER" (
	"MEM_CODE"
);

ALTER TABLE "DAILY_ WAGE" ADD CONSTRAINT "FK_OVERTIME_WORK_TO_DAILY_ WAGE_1" FOREIGN KEY (
	"OVERTIME_WORK_CODE"
)
REFERENCES "OVERTIME_WORK" (
	"OVERTIME_WORK_CODE"
);

ALTER TABLE "ATTEND_REGIST" ADD CONSTRAINT "FK_MEMBER_TO_ATTEND_REGIST_1" FOREIGN KEY (
	"MEM_CODE"
)
REFERENCES "MEMBER" (
	"MEM_CODE"
);

ALTER TABLE "ADJUSTING_ATTENDANCE" ADD CONSTRAINT "FK_APPLICATION_WORK_SCHEDULE_TO_ADJUSTING_ATTENDANCE_1" FOREIGN KEY (
	"SCHEDULE_NUMBER"
)
REFERENCES "APPLICATION_WORK_SCHEDULE" (
	"SCHEDULE_NUMBER"
);

ALTER TABLE "ADJUSTING_ATTENDANCE" ADD CONSTRAINT "FK_REPORTER_TAG_TO_ADJUSTING_ATTENDANCE_1" FOREIGN KEY (
	"REPORTER_TAG_CODE"
)
REFERENCES "REPORTER_TAG" (
	"REPORTER_TAG_CODE"
);

ALTER TABLE "ADJUSTING_ATTENDANCE" ADD CONSTRAINT "FK_DOCUMENT_APPROVAL_TO_ADJUSTING_ATTENDANCE_1" FOREIGN KEY (
	"DOCUMENT_NUMBER"
)
REFERENCES "DOCUMENT_APPROVAL" (
	"DOCUMENT_NUMBER"
);

ALTER TABLE "REPORTER_TAG" ADD CONSTRAINT "FK_MEMBER_TO_REPORTER_TAG_1" FOREIGN KEY (
	"MEM_CODE"
)
REFERENCES "MEMBER" (
	"MEM_CODE"
);

ALTER TABLE "APPLICATION_OVERTIME_WORK" ADD CONSTRAINT "FK_MEMBER_TO_APPLICATION_OVERTIME_WORK_1" FOREIGN KEY (
	"MEM_CODE"
)
REFERENCES "MEMBER" (
	"MEM_CODE"
);

ALTER TABLE "APPLICATION_OVERTIME_WORK" ADD CONSTRAINT "FK_REPORTER_TAG_TO_APPLICATION_OVERTIME_WORK_1" FOREIGN KEY (
	"REPORTER_TAG_CODE"
)
REFERENCES "REPORTER_TAG" (
	"REPORTER_TAG_CODE"
);

ALTER TABLE "APPLICATION_OVERTIME_WORK" ADD CONSTRAINT "FK_WORK_SETTING_TO_APPLICATION_OVERTIME_WORK_1" FOREIGN KEY (
	"WORK_SETTING_NUMBER"
)
REFERENCES "WORK_SETTING" (
	"WORK_SETTING_NUMBER"
);

ALTER TABLE "APPLICATION_OVERTIME_WORK" ADD CONSTRAINT "FK_DOCUMENT_APPROVAL_TO_APPLICATION_OVERTIME_WORK_1" FOREIGN KEY (
	"DOCUMENT_NUMBER"
)
REFERENCES "DOCUMENT_APPROVAL" (
	"DOCUMENT_NUMBER"
);

ALTER TABLE "ANNUAL_MAKE" ADD CONSTRAINT "FK_MEMBER_TO_ANNUAL_MAKE_1" FOREIGN KEY (
	"MEM_CODE"
)
REFERENCES "MEMBER" (
	"MEM_CODE"
);

ALTER TABLE "ANNUAL_USE" ADD CONSTRAINT "FK_ANNUAL_MAKE_TO_ANNUAL_USE_1" FOREIGN KEY (
	"ANNUAL_MAKE_NUMER"
)
REFERENCES "ANNUAL_MAKE" (
	"ANNUAL_MAKE_NUMER"
);

ALTER TABLE "ANNUAL_USE" ADD CONSTRAINT "FK_APPLICATION_VACATION_TO_ANNUAL_USE_1" FOREIGN KEY (
	"VACATION_NUBER"
)
REFERENCES "APPLICATION_VACATION" (
	"VACATION_NUBER"
);

ALTER TABLE "APPLICATION_VACATION" ADD CONSTRAINT "FK_VACATION_CATEGORY_TO_APPLICATION_VACATION_1" FOREIGN KEY (
	"VACATION_CODE"
)
REFERENCES "VACATION_CATEGORY" (
	"VACATION_CODE"
);

ALTER TABLE "APPLICATION_VACATION" ADD CONSTRAINT "FK_ALLDAY_CATEGORY_TO_APPLICATION_VACATION_1" FOREIGN KEY (
	"ALLDAY_CODE"
)
REFERENCES "ALLDAY_CATEGORY" (
	"ALLDAY_CODE"
);

ALTER TABLE "APPLICATION_VACATION" ADD CONSTRAINT "FK_REPORTER_TAG_TO_APPLICATION_VACATION_1" FOREIGN KEY (
	"REPORTER_TAG_CODE"
)
REFERENCES "REPORTER_TAG" (
	"REPORTER_TAG_CODE"
);

ALTER TABLE "APPLICATION_VACATION" ADD CONSTRAINT "FK_DOCUMENT_APPROVAL_TO_APPLICATION_VACATION_1" FOREIGN KEY (
	"DOCUMENT_NUMBER"
)
REFERENCES "DOCUMENT_APPROVAL" (
	"DOCUMENT_NUMBER"
);

ALTER TABLE "DOCUMENT_APPROVAL" ADD CONSTRAINT "FK_APPROVED_CATEGORY_TO_DOCUMENT_APPROVAL_1" FOREIGN KEY (
	"APPROVED__CODE"
)
REFERENCES "APPROVED_CATEGORY" (
	"APPROVED__CODE"
);

ALTER TABLE "DOCUMENT_APPROVAL" ADD CONSTRAINT "FK_APPLICATION_VACATION_TO_DOCUMENT_APPROVAL_1" FOREIGN KEY (
	"VACATION_NUBER"
)
REFERENCES "APPLICATION_VACATION" (
	"VACATION_NUBER"
);

ALTER TABLE "DOCUMENT_APPROVAL" ADD CONSTRAINT "FK_APPLICATION_OVERTIME_WORK_TO_DOCUMENT_APPROVAL_1" FOREIGN KEY (
	"OVERTIME_NUMBER"
)
REFERENCES "APPLICATION_OVERTIME_WORK" (
	"OVERTIME_NUMBER"
);

ALTER TABLE "DOCUMENT_APPROVAL" ADD CONSTRAINT "FK_ADJUSTING_ATTENDANCE_TO_DOCUMENT_APPROVAL_1" FOREIGN KEY (
	"ADJUST_ATTEND_NUMBER"
)
REFERENCES "ADJUSTING_ATTENDANCE" (
	"ADJUST_ATTEND_NUMBER"
);

ALTER TABLE "DOCUMENT_APPROVAL" ADD CONSTRAINT "FK_APPLICATION_WORK_SCHEDULE_TO_DOCUMENT_APPROVAL_1" FOREIGN KEY (
	"SCHEDULE_NUMBER"
)
REFERENCES "APPLICATION_WORK_SCHEDULE" (
	"SCHEDULE_NUMBER"
);

ALTER TABLE "BONUS_LIST" ADD CONSTRAINT "FK_MEMBER_TO_BONUS_LIST_1" FOREIGN KEY (
	"MEM_CODE"
)
REFERENCES "MEMBER" (
	"MEM_CODE"
);

ALTER TABLE "BONUS_LIST" ADD CONSTRAINT "FK_BONUS_TO_BONUS_LIST_1" FOREIGN KEY (
	"BONUS_CODE"
)
REFERENCES "BONUS" (
	"BONUS_CODE"
);

ALTER TABLE "BONUS_LIST" ADD CONSTRAINT "FK_TAXATION_TO_BONUS_LIST_1" FOREIGN KEY (
	"TAXATION_CODE"
)
REFERENCES "TAXATION" (
	"TAXATION_CODE"
);

ALTER TABLE "BONUS_LIST" ADD CONSTRAINT "FK_TAX_FREE_TO_BONUS_LIST_1" FOREIGN KEY (
	"TAX_FREE_CODE"
)
REFERENCES "TAX_FREE" (
	"TAX_FREE_CODE"
);

ALTER TABLE "CCAPPLICATION" ADD CONSTRAINT "FK_APPROVAL_TO_CCAPPLICATION_1" FOREIGN KEY (
	"DOC_CODE"
)
REFERENCES "APPROVAL" (
	"DOC_CODE"
);

ALTER TABLE "CCAPPLICATION" ADD CONSTRAINT "FK_APPROVAL_TO_CCAPPLICATION_2" FOREIGN KEY (
	"MEM_CODE"
)
REFERENCES "APPROVAL" (
	"MEM_CODE"
);

ALTER TABLE "CCAPPLICATION" ADD CONSTRAINT "FK_EXPENSECONGRATULATIONSCONDOLENCES_TO_CCAPPLICATION_1" FOREIGN KEY (
	"CC_CODE"
)
REFERENCES "EXPENSECONGRATULATIONSCONDOLENCES" (
	"CC_CODE"
);

ALTER TABLE "CERTIFICATEAPPLICATION" ADD CONSTRAINT "FK_APPROVAL_TO_CERTIFICATEAPPLICATION_1" FOREIGN KEY (
	"DOC_CODE"
)
REFERENCES "APPROVAL" (
	"DOC_CODE"
);

ALTER TABLE "CERTIFICATEAPPLICATION" ADD CONSTRAINT "FK_APPROVAL_TO_CERTIFICATEAPPLICATION_2" FOREIGN KEY (
	"MEM_CODE"
)
REFERENCES "APPROVAL" (
	"MEM_CODE"
);

ALTER TABLE "CERTIFICATEAPPLICATION" ADD CONSTRAINT "FK_CERTIFICATE_TO_CERTIFICATEAPPLICATION_1" FOREIGN KEY (
	"CER_CODE"
)
REFERENCES "CERTIFICATE" (
	"CER_CODE"
);

ALTER TABLE "ANNUAL_INCOME" ADD CONSTRAINT "FK_MEMBER_TO_ANNUAL_INCOME_1" FOREIGN KEY (
	"MEM_CODE"
)
REFERENCES "MEMBER" (
	"MEM_CODE"
);

ALTER TABLE "MONTHLY_WAGE" ADD CONSTRAINT "FK_MEMBER_TO_MONTHLY_WAGE_1" FOREIGN KEY (
	"MEM_CODE"
)
REFERENCES "MEMBER" (
	"MEM_CODE"
);

ALTER TABLE "EMPLOYEE_SALARY_SETTING" ADD CONSTRAINT "FK_MEMBER_TO_EMPLOYEE_SALARY_SETTING_1" FOREIGN KEY (
	"MEM_CODE"
)
REFERENCES "MEMBER" (
	"MEM_CODE"
);

